import java.util.Scanner;
import java.util.Random;
public class ChineseProverb {
    private static final String[] PROVERBS = {
            "To, co nie wydasz na kucharza, wydasz na lekarza.",
            "Śniadanie zjedz sam, obiadem podziel się z przyjacielem, a kolację oddaj wrogowi.",
            "Jeśli 50-letniego mężczyznę po przebudzeniu nic nie boli, to znaczy, że ten mężczyzna nie żyje.",
            "Lekarz może wyleczyć z choroby, ale nie z losu.",
            "Choroba jest uleczalna, nie przeznaczenie.",
            "Szczęśliwy lekarz spotyka chorego przy końcu jego choroby, a nieszczęśliwy przy jej początku.",
            "Lek nie uleczy wymyślonej choroby, a wódka nie uleczy prawdziwego smutku.",
            "Żołądek pełen lekarstw i koszula łatana długo nie wytrzymują.",
            "Serce nigdy nie mówi, ale musisz go słuchać, aby je zrozumieć.",
            "Nie można błagać o miłość, trzeba na nią zasłużyć.",
            "Róża jest piękniejsza niż kapusta, lecz zupa z róży jest gorsza niż kapuśniak. (nawiązanie do urody i związków)",
            "Pewien mąż tak kochał swoją jednooką żonę, że stwierdził, iż wszystkie inne kobiety mają jedno oko za dużo.",
            "Zwykle mąż i żona żyją jak dwa ptaszki w tym samym lesie, ale w nieszczęściu rozlatują się, każde w swoją stronę.",
            "Żony szukamy dla jej cnoty, a nałożnicy dla jej urody.",
            "W małżeństwie nikt nie mówi prawdy, przed przyjaciółmi nikt nie kłamie.",
            "Zły syn kocha żonę i sprzeciwia się matce, niedobra matka dręczy synową.",
            "Wysoko w niebo wzbija się dym z komina, jeżeli wszyscy w rodzinie zbierają chrust.",
            "Życie dziecka jest jak kartka papieru, na której każdy zostawia ślad.",
            "Język jest bronią kobiet – nigdy nie pozwalają jej zardzewieć.",
            "Język kobiety jest krótki, ale rani mężczyznę bardzo głęboko.",
            "Los pięknych kobiet jest nieszczęśliwy, wybitni mężczyźni rzadko bywają urodziwi.",
            "Mężczyzna uważa, że wie, ale kobieta wie lepiej.",
            "Milczeniem nigdy sobie kobieta sprawy nie popsuła.",
            "Dla mężczyzny cnota jest talentem, dla kobiet brak talentów jest cnotą.",
            "Nawet wielki słoń zaplącze się w kobiece włosy.",
            "Umysł kobiety – żywe srebro, a ich serca to wosk.",
            "Wstyd jest męstwem płci pięknej, milczenie i rumieniec – wymową.",
            "Ubrania są bardziej cenne, gdy są nowe, ale relacje z ludźmi są bardziej cenne, gdy są stare.",
            "Sprawiedliwość ma siedzibę w ludzkim sercu.",
            "Za krzywdę płać sprawiedliwością, łaskę opłacaj łaską.",
            "Po jednym spotkaniu łatwo się zaprzyjaźnić, ale razem mieszkając, łatwo się pokłócić.",
            "Dla przychodniów bądź gościnny, dla sąsiadów – pomocnym, dla poczciwych – przyjacielem, a dla złych obcym.",
            "Bądźcie surowi dla samych siebie, pobłażliwi dla innych, a nie będziecie mieli wrogów.",
            "Największym grzechem jest nie uratować ginącego życia.",
            "Droga ujawnia prawdziwą siłę konia, a czas prawdziwe serce człowieka.",
            "Głodnemu daj kawałek chleba, a smutnemu kawałek serca.",
            "Spokojnie rozważaj własne błędy, a w rozmowie nie zajmuj się cudzymi winami.",
            "W obliczu śmierci głodowej nikt nie zachowa etykiety.",
            "Biedny boi się krewnych, a bogaty złodziei.",
            "Wstrzemięźliwy człowiek z czerwonym nosem uchodzi za pijaka.",
            "Prawdziwe słowa nie są piękne, a słowa piękne nie są prawdziwe.",
            "W zbyt czystej wodzie nie ma ryb.",
            "Po długiej wizycie krótkie pożegnanie.",
            "Sto dzikich kaczek podrywa się nie dlatego, że jedna zakwakała, lecz dlatego, że się poderwała.",
            "To, co słyszysz, może być fałszywe, ale to, co widzisz, jest prawdą.",
            "We fragmentach prawdy mało, albo nie ma prawdy wcale.",
            "Słowa raz powiedzianego nie cofniesz nawet zaprzęgiem czterech koni.",
            "Językiem można zmiażdżyć drugiego człowieka.",
            "Zwyczaj wpływa na wszystkich, i nikt mu się nie może oprzeć.",
            "Sąd jednego człowieka nic nie znaczy wobec opinii powszechnej.",
            "Istnieje tylko dwóch dobrych ludzi – jeden zmarł, a drugi się jeszcze nie narodził.",
            "Wąż nie zmieni swojej krętej natury, nawet kiedy się wśliźnie w prostą rurę bambusową.",
            "To, co się powie człowiekowi prosto w twarz – nie jest plotką.",
            "Przyjemności są powierzchowne, ale przykrości sięgają głęboko.",
            "Wszystko na początku wydaje się być trudne.",
            "Zamierzając dokonać czegoś wielkiego, od małego zaczynaj.",
            "Porażka jest matką sukcesu.",
            "Jeśli pracujesz nad tym wystarczająco ciężko, możesz zmielić nawet żelazny pręt do igły.",
            "Planowanie dnia odbywa się o świcie.",
            "Gdy za dużo murarzy, dom staje się krzywy.",
            "Najwięcej czasu ma człowiek, który niczego nie odkłada na później.",
            "Gdy wieją wichry zmian jedni budują mury, a inni wiatraki.",
            "Czas kosztuje złoto, ale za złoto czasu nie kupisz.",
            "Szlachetny mąż najpierw działa, potem mówi, a słowa jego zgodne są z czynami.",
            "Tylko ci, co robią powoli to, co inni robią w pośpiechu, są w stanie zrobić prędko to, co inni muszą robić powoli.",
            "Jedna rozmowa z mądrym człowiekiem jest warta tyle, ile miesiąc czytania książek.",
            "Miej oczy szeroko otwarte, a usta otwieraj powoli.",
            "Nie kłóć się z głupim, bo postronni nie zauważą różnicy.",
            "Wszyscy są mądrzy: jedni przedtem, inni potem.",
            "Aby być mądrym, nie wystarczy mieć wiele ksiąg: osioł dźwigający na grzbiecie wiele książek nie jest przez to mądrzejszy.",
            "Kto nie pyta wcale, pozostaje głupcem przez całe życie.",
            "Najwięcej rozumu trzeba wtedy, gdy ma się do czynienia z głupcami.",
            "By nie móc spojrzeć na wódkę, trzeba spojrzeć na pijaka.",
            "Można utopić rozum w winie, ale nieszczęścia utopić się nie da.",
            "Pijaństwo nie tworzy wad – ono je ujawnia.",
            "Ten, kto ma wino, powinien pić za życia, bo żadna kropla nie przedostanie się na tamten świat.",
            "To nie wino upija człowieka, to człowiek upija się sam.",
            "Człowiek całe życie prześpi, jeśli wierzy w swoje sny.",
            "Potrzeba więcej niż jednego zimnego dnia, aby rzeka zamarzła na głębokości trzech stóp.",
            "Starzejący się imbir jest bardziej pikantny. (Wiedzy nabieramy z wiekiem)",
            "Życie człowieka jest jak sen wiosenny, a bogactwa i zachwyty jak przemijające chmurki.",
            "Wielka rzecz umieć czekać.",
            "Umierający ptak wydaje żałosne dźwięki; umierający człowiek wygłasza mądre zdania.",
            "Dobre przypadki zdarzają się zwykle tym, którzy mają wiele optymizmu.",
            "Jeśli zbłądzisz, nie oskarżaj o to nieba, a jeśli się potkniesz, nie oskarżaj o to ziemi.",
            "Obserwuj, aż chmury się rozejdą, aby zobaczyć światło księżyca. (Gdy sprawy źle się toczą, oczekuj zmiany na dobre.)",
            "Ludzie chociaż nie dożyją nawet stu lat, to stwarzają sobie troski na całe tysiąclecia.",
            "Nie możesz zatrzymać żadnego dnia, ale możesz go nie stracić.",
            "Gdy nie masz nic do ofiarowania, ofiaruj uśmiech.",
            "Spokojna odpowiedź przepędza gniew.",
            "Żyj tak, by w twej ostatniej godzinie płakali wszyscy inni, a ty jeden byś się śmiał serdecznie i łzy nie miał w oku.",
            "Kiedy człowiek kroczy drogą Środka, nawet jego zwierzęta wstępują do Nieba.",
            "Przypadkowe wykroczenie jest błędem, świadome jest winą.",
            "Zanim zaczniesz poprawiać świat, przejdź się trzy razy przez swój własny dom.",
            "Zjesz niegotowane mięso – zaszkodzi żołądkowi. Powiesz nieprzyzwoite słowo – zaszkodzi całemu tobie.",
            "Jeśli zdobędziesz się na cierpliwość w jednej chwili gniewu, zaoszczędzisz sobie sto dni przykrości.",
            "Trzy razy pomyśl, zanim coś zrobisz, a nie będziesz żałował swych czynów.",
            "I ogień, i woda są nieczułe na ludzkie cierpienia.",
            "Błąd chwili staje się troską całego życia.",
            "Kto nie karmi psa, karmi złodzieja.",
            "Najwspanialsza pamięć jest słabsza niż najsłabszy atrament.",
            "Pycha przynosi zgubę, skromność i umiarkowanie przynoszą korzyści."
    };
    public static void main(String[] args) {
        proverb();
    }
    public static void proverb() {
        Random random = new Random();
        int RandomInt = random.nextInt(100) + 1;
        System.out.println("UWAGA UWAGA!!!!!\nChińskie porzekadło na dziś to:");
        System.out.println(PROVERBS[RandomInt]);
    }
}